services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app

  backend:
    build: ./backend
    expose:
      - "8000"
    networks:
      - app

  frontend:
    build: ./frontend
    expose:
      - "8001"
    networks:
      - app

networks:
  app: